# Generated by Django 4.2 on 2023-04-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0005_brand_rename_mobile_num_customer_mobile_cus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='brand_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='supplier',
            new_name='supplier_id',
        ),
    ]
