# Generated by Django 4.2 on 2023-04-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0007_alter_customer_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_name',
            new_name='supplier_id',
        ),
    ]
