# Generated by Django 4.2 on 2023-04-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0011_brand_customer_supplier_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
