# Generated by Django 4.2 on 2023-04-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0012_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_name',
            new_name='name',
        ),
    ]
